// @ts-nocheck
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf -t 
Author: Apple User (https://sketchfab.com/apple-user)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/macbook-pro-14-inch-m5-652a992f4f244122ae251f9cbb81da1e
Title: MacBook Pro 14-inch M5
*/

import {TactileKeyboard} from './TactileKeyboard';
import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_12: THREE.Mesh
    Object_14: THREE.Mesh
    Object_16: THREE.Mesh
    Object_20: THREE.Mesh
    Object_22: THREE.Mesh
    Object_24: THREE.Mesh
    Object_26: THREE.Mesh
    Object_28: THREE.Mesh
    Object_30: THREE.Mesh
    Object_32: THREE.Mesh
    Object_35: THREE.Mesh
    Object_37: THREE.Mesh
    Object_40: THREE.Mesh
    Object_42: THREE.Mesh
    Object_44: THREE.Mesh
    Object_48: THREE.Mesh
    Object_50: THREE.Mesh
    Object_53: THREE.Mesh
    Object_55: THREE.Mesh
    Object_57: THREE.Mesh
    Object_59: THREE.Mesh
    Object_62: THREE.Mesh
    Object_64: THREE.Mesh
    Object_67: THREE.Mesh
    Object_69: THREE.Mesh
    Object_71: THREE.Mesh
    Object_73: THREE.Mesh
    Object_75: THREE.Mesh
    Object_77: THREE.Mesh
    Object_79: THREE.Mesh
    Object_83: THREE.Mesh
    Object_85: THREE.Mesh
    Object_87: THREE.Mesh
    Object_89: THREE.Mesh
    Object_91: THREE.Mesh
    Object_94: THREE.Mesh
    Object_96: THREE.Mesh
    Object_98: THREE.Mesh
    Object_100: THREE.Mesh
    Object_103: THREE.Mesh
    Object_105: THREE.Mesh
    Object_107: THREE.Mesh
    Object_109: THREE.Mesh
    Object_111: THREE.Mesh
  }
  materials: {
    zNRfbdNyoCOxSDD: THREE.MeshStandardMaterial
    HdeQgqDhVRltuvQ: THREE.MeshStandardMaterial
    MTVWTmEddByGzeA: THREE.MeshStandardMaterial
    gGmExFByNnyrwMm: THREE.MeshStandardMaterial
    GdPtFLZURIXFHzu: THREE.MeshStandardMaterial
    cFRLiGCORrjAihr: THREE.MeshStandardMaterial
    TMkvtqywJDMvuJf: THREE.MeshStandardMaterial
    jgUGvZiSIPFNFGe: THREE.MeshStandardMaterial
    GzMrvkTsmRxvOJz: THREE.MeshStandardMaterial
    IqdrVPEOaZqbHHo: THREE.MeshStandardMaterial
    HzlgDKVNnMxfNgM: THREE.MeshStandardMaterial
    vJOGifqMXcmlCkF: THREE.MeshStandardMaterial
    XvtJEVWVvyDeJRR: THREE.MeshStandardMaterial
    ItKEDAaOJloGKSH: THREE.MeshStandardMaterial
    xEcnbqMzoZoLkIZ: THREE.MeshStandardMaterial
    YMmdfGRsPviDXYd: THREE.MeshStandardMaterial
    kMkIQgtfAZdmtyc: THREE.MeshStandardMaterial
    sqkqSXQCeccDMmm: THREE.MeshStandardMaterial
    utAQarMJnpKrQeb: THREE.MeshStandardMaterial
    waAAeDqzqDLObIi: THREE.MeshStandardMaterial
    quuXrfeUujYrUMo: THREE.MeshStandardMaterial
    WiyOPYJEeiHNVjF: THREE.MeshStandardMaterial
    KtCwfhzYtafEPLg: THREE.MeshStandardMaterial
    uHOYziIuFeQJbIX: THREE.MeshStandardMaterial
    DthpMXUDOFLFvyk: THREE.MeshStandardMaterial
    pKaDkdyuuvylYHt: THREE.MeshPhysicalMaterial
    ZtrFkpzRROyZncn: THREE.MeshStandardMaterial
    HlQwFCAPWzetDQy: THREE.MeshPhysicalMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/macbook.glb/scene.gltf') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <TactileKeyboard nodes={nodes} />
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group scale={0.01}>
          <mesh geometry={nodes.Object_12.geometry} material={materials.zNRfbdNyoCOxSDD} />
          <mesh geometry={nodes.Object_14.geometry} material={materials.HdeQgqDhVRltuvQ} />
          <mesh geometry={nodes.Object_16.geometry} material={materials.HdeQgqDhVRltuvQ} />
          <mesh geometry={nodes.Object_20.geometry} material={materials.MTVWTmEddByGzeA} />
          <mesh geometry={nodes.Object_22.geometry} material={materials.gGmExFByNnyrwMm} />
          <mesh geometry={nodes.Object_24.geometry} material={materials.GdPtFLZURIXFHzu} />
          <mesh geometry={nodes.Object_26.geometry} material={materials.cFRLiGCORrjAihr} />
          <mesh geometry={nodes.Object_28.geometry} material={materials.MTVWTmEddByGzeA} />
          <mesh geometry={nodes.Object_30.geometry} material={materials.TMkvtqywJDMvuJf} />
          <mesh geometry={nodes.Object_32.geometry} material={materials.jgUGvZiSIPFNFGe} />
          <mesh geometry={nodes.Object_35.geometry} material={materials.GzMrvkTsmRxvOJz} />
          <mesh geometry={nodes.Object_37.geometry} material={materials.IqdrVPEOaZqbHHo} />
          <mesh geometry={nodes.Object_40.geometry} material={materials.gGmExFByNnyrwMm} />
          <mesh geometry={nodes.Object_42.geometry} material={materials.IqdrVPEOaZqbHHo} />
          <mesh geometry={nodes.Object_44.geometry} material={materials.HzlgDKVNnMxfNgM} />
          <mesh geometry={nodes.Object_48.geometry} material={materials.vJOGifqMXcmlCkF} />
          <mesh geometry={nodes.Object_50.geometry} material={materials.XvtJEVWVvyDeJRR} />
          <mesh geometry={nodes.Object_53.geometry} material={materials.ItKEDAaOJloGKSH} />
          <mesh geometry={nodes.Object_55.geometry} material={materials.xEcnbqMzoZoLkIZ} />
          <mesh geometry={nodes.Object_57.geometry} material={materials.XvtJEVWVvyDeJRR} />
          <mesh geometry={nodes.Object_59.geometry} material={materials.XvtJEVWVvyDeJRR} />
          <mesh geometry={nodes.Object_62.geometry} material={materials.YMmdfGRsPviDXYd} />
          <mesh geometry={nodes.Object_64.geometry} material={materials.HdeQgqDhVRltuvQ} />
          <mesh geometry={nodes.Object_67.geometry} material={materials.kMkIQgtfAZdmtyc} />
          <mesh geometry={nodes.Object_69.geometry} material={materials.sqkqSXQCeccDMmm} />
          <mesh geometry={nodes.Object_71.geometry} material={materials.utAQarMJnpKrQeb} />
          <mesh geometry={nodes.Object_73.geometry} material={materials.waAAeDqzqDLObIi} />
          <mesh geometry={nodes.Object_75.geometry} material={materials.quuXrfeUujYrUMo} />
          <mesh geometry={nodes.Object_77.geometry} material={materials.WiyOPYJEeiHNVjF} />
          <mesh geometry={nodes.Object_79.geometry} material={materials.gGmExFByNnyrwMm} />
          <mesh geometry={nodes.Object_83.geometry} material={materials.KtCwfhzYtafEPLg} />
          <mesh geometry={nodes.Object_85.geometry} material={materials.gGmExFByNnyrwMm} />
          <mesh geometry={nodes.Object_87.geometry} material={materials.uHOYziIuFeQJbIX} />
          <mesh geometry={nodes.Object_89.geometry} material={materials.gGmExFByNnyrwMm} />
          <mesh geometry={nodes.Object_91.geometry} material={materials.DthpMXUDOFLFvyk} />
          <mesh geometry={nodes.Object_94.geometry} material={materials.vJOGifqMXcmlCkF} />
          <mesh geometry={nodes.Object_96.geometry} material={materials.HdeQgqDhVRltuvQ} />
          <mesh geometry={nodes.Object_98.geometry} material={materials.IqdrVPEOaZqbHHo} />
          <mesh geometry={nodes.Object_100.geometry} material={materials.pKaDkdyuuvylYHt} />
          <mesh geometry={nodes.Object_103.geometry} material={materials.gGmExFByNnyrwMm} />
          <mesh geometry={nodes.Object_105.geometry} material={materials.ZtrFkpzRROyZncn} />
          <mesh geometry={nodes.Object_107.geometry} material={materials.HlQwFCAPWzetDQy} />
          <mesh geometry={nodes.Object_109.geometry} material={materials.IqdrVPEOaZqbHHo} />
          <mesh geometry={nodes.Object_111.geometry} material={materials.gGmExFByNnyrwMm} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/macbook.glb/scene.gltf')
